#!/bin/bash

echo "alias s='sudo su -'" >> /home/ec2-user/.bashrc

yum -y update
yum install -y httpd php php-mysql 


wget https://wordpress.org/wordpress-5.1.1.tar.gz
tar xzf wordpress-5.1.1.tar.gz -C /var/www/html/
mv /var/www/html/wordpress/* /var/www/html/

rmdir /var/www/html/wordpress/
rm -rf wordpress-5.1.1.tar.gz

chmod -R 755 /var/www/html/wp-content
chown -R apache:apache /var/www/html/wp-content

systemctl start httpd
systemctl enable httpd
